<link rel="stylesheet" type="text/css" href="../menu/style.css" media="all">
<div id="tabs24">
	<ul>
		<li><a href="funcInsert.php" title="css menus"><span>Cadastrar</span></a></li>
		<li><a href="funcUpdate.php" title="css menus"><span>Alterar</span></a></li>
		<li><a href="funcDelete.php" title="css menus"><span>Excluir</span></a></li>
        <li><a href="funcSelect.php" title="css menus"><span>Relatório por Código</span></a></li>		
	</ul>
</div>

